import { defineField, defineType } from 'sanity';

export const instructorType = defineType({
    name: 'instructor',
    title: 'Instructor (클래스 강사)',
    type: 'document',
    fields: [
        defineField({
            name: 'id',
            title: '고유 ID',
            type: 'slug',
            description: '고유 ID (악기명-강사이름-t 형식 권장, 예: flute-parkig-t)',
            validation: (Rule) => Rule.required(),
            options: {
                source: 'instructorName',
                maxLength: 96,
            },
        }),
        defineField({
            name: 'order',
            title: '정렬 순서(Order)',
            type: 'number',
            description: '리스트에서 보여질 순서 (숫자가 작을수록 먼저 노출됩니다)',
            validation: (Rule) => Rule.required(),
            initialValue: 0,
        }),
        defineField({
            name: 'category',
            title: '클래스 카테고리',
            type: 'string',
            description: '영문 대문자 클래스명 (예: FLUTE CLASS)',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'instructorName',
            title: '강사명',
            type: 'string',
            description: '강사명 (통일성을 위해 한글 이름만 작성, 영문 괄호X)',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'image',
            title: '좌측 썸네일 (리스트 화면용)',
            type: 'image',
            description: '좌측 박스에 들어갈 이미지 (배경 투명을 위해 svg 권장)',
            options: { hotspot: true },
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'imagePosition',
            title: '썸네일 위치/크기 (Tailwind 클래스)',
            type: 'string',
            description: '이미지 위치 및 크기 조정 (예: object-top 또는 object-top scale-[1.5] origin-[center_10%])',
            initialValue: 'object-top',
        }),
        defineField({
            name: 'modalImage',
            title: '원본 사진 (모달 화면용)',
            type: 'image',
            description: '팝업창 안의 사각형 프레임에 들어갈 퓨어한 원본 사진 (비워두면 좌측 썸네일이 그대로 들어감)',
            options: { hotspot: true },
        }),
        defineField({
            name: 'bgImage',
            title: '우측 배경 은은한 이미지 (리스트 호버용)',
            type: 'image',
            description: '우측에 크게 나타나는 배경용 흑백/투명 이미지',
            options: { hotspot: true },
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'bgScale',
            title: '배경 이미지 상하 크기 (Tailwind)',
            type: 'string',
            description: '배경 이미지 상하 크기 조절 (h-[85%] 또는 h-full 등을 입력)',
            initialValue: 'h-full',
        }),
        defineField({
            name: 'bgPosition',
            title: '배경 이미지 위치 여백 (Tailwind)',
            type: 'string',
            description: '배경 이미지 여백 및 정렬 위치 (예: bottom-0 right-0 md:right-12)',
            initialValue: 'bottom-0 right-0 md:right-12',
        }),
        defineField({
            name: 'subtitle',
            title: '서브타이틀 (캐치프레이즈)',
            type: 'string',
            description: '모달 안 제목 아래 들어갈 캐치프레이즈',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'lessonInfo',
            title: '레슨 형태 정보',
            type: 'string',
            description: '예: 1:1 Private & Group Lesson',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'about',
            title: '레슨 소개',
            type: 'array',
            of: [{ type: 'string' }],
            description: '줄바꿈(문단)별로 항목을 추가해주세요.',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'process',
            title: '커리큘럼 / 프로세스',
            type: 'array',
            of: [{ type: 'string' }],
            description: '줄바꿈(문단)별로 항목을 추가해주세요.',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'portfolioUrl',
            title: '작업물(포트폴리오) 유튜브/링크 URL',
            type: 'url',
            description: '작업물 외부 링크 주소 (https://...)',
        }),
        defineField({
            name: 'portfolioText',
            title: '작업물 설명 텍스트',
            type: 'text',
            description: '버튼 위에 표시되는 설명',
        }),
        defineField({
            name: 'portfolioBtn',
            title: '작업물 버튼 이름',
            type: 'string',
            description: '버튼 텍스트 (예: 작업물 듣기, 작업물 보기)',
            initialValue: '작업물 보기',
        }),
    ],
    preview: {
        select: {
            title: 'instructorName',
            subtitle: 'category',
            media: 'image',
        },
    },
});
